// Generated by https://quicktype.io

export interface IData {
  data: IDatum[];
}

export interface IDatum {
  id: string;
  items: Item[];
  title: string;
}

export interface Item {
  title: string;
  photoUrL: string;
  id: string;
}
