import Head from 'next/head'
import React from 'react'
import { colors } from '../utilities/colors';
import { Container } from './LayoutStyle';

interface LayoutProps {
    children: React.ReactNode
}

export const Layout = ({ children }: LayoutProps) => {
    return (
        <>
            <Head>
                <title>DailyPay - Challenge</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container suppressHydrationWarning={true}>
                {children}
            </Container>
        </>

    )
}
